[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Eugene Pimenov <eugene@libc.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crossbeam = "0.7.3"
termion = "1.5.4"
im = "10.2.0"
ndarray = "0.13.0"
